Upgrade tooling for 9.0x (#5483)
* Update dependencies from ".NET 9 Eng" channel

Updating 'Microsoft.SourceBuild.Intermediate.source-build-reference-packages': '8.0.0-alpha.1.23516.4' => '9.0.0-alpha.1.24453.2' (from build '20240903.2' of 'https://github.com/dotnet/source-build-reference-packages')
Updating 'Microsoft.SourceBuild.Intermediate.arcade': '8.0.0-beta.24426.2' => '9.0.0-beta.24453.1' (from build '20240903.1' of 'https://github.com/dotnet/arcade')
Updating 'Microsoft.DotNet.Arcade.Sdk': '8.0.0-beta.24426.2' => '9.0.0-beta.24453.1' (from build '20240903.1' of 'https://github.com/dotnet/arcade')
Updating 'Microsoft.DotNet.Build.Tasks.Installers': '8.0.0-beta.24426.2' => '9.0.0-beta.24453.1' (from build '20240903.1' of 'https://github.com/dotnet/arcade')
Updating 'Microsoft.DotNet.Build.Tasks.Workloads': '8.0.0-beta.24426.2' => '9.0.0-beta.24453.1' (from build '20240903.1' of 'https://github.com/dotnet/arcade')
Updating 'Microsoft.DotNet.Helix.Sdk': '8.0.0-beta.24426.2' => '9.0.0-beta.24453.1' (from build '20240903.1' of 'https://github.com/dotnet/arcade')
Updating 'Microsoft.DotNet.RemoteExecutor': '8.0.0-beta.24426.2' => '9.0.0-beta.24453.1' (from build '20240903.1' of 'https://github.com/dotnet/arcade')
Updating 'Microsoft.DotNet.SharedFramework.Sdk': '8.0.0-beta.24426.2' => '9.0.0-beta.24453.1' (from build '20240903.1' of 'https://github.com/dotnet/arcade')
Updating 'Microsoft.DotNet.XUnitExtensions': '8.0.0-beta.24426.2' => '9.0.0-beta.24453.1' (from build '20240903.1' of 'https://github.com/dotnet/arcade')

* Add dotnet 8 versions for testing

* [tests] Install 8.0 runtime for workload testing

* Resolve xUnit2013 warning

`Do not use Assert.Equal() to check for collection size. Use
Assert.Single instead.xUnit2013`

* Resolve xUnit2029 warning

`Do not use Assert.Empty() to check if a value does not exist in a
collection. Use Assert.DoesNotContain() instead.xUnit2029`

* Track API change in EqualException

* Ignore warning xUnit1030

`error xUnit1030: Test methods should not call ConfigureAwait(false), as
it may bypass parallelization limits. Omit ConfigureAwait, or use
ConfigureAwait(true) to avoid CA2007.
(https://xunit.net/xunit.analyzers/rules/xUnit1030)`

* Fix xUnit1012 analyzer warning.

Warning of the form:
`error xUnit1012: Null should not be used for type parameter
'secondaryApiKey' of type 'string'. Use a non-null value, or convert the
parameter to a nullable type.
(https://xunit.net/xunit.analyzers/rules/xUnit1012)`

* Fix compile error.

`error CS0121: The call is ambiguous between the following methods or
properties: 'Assert.Contains<T>(T, HashSet<T>)' and
'Assert.Contains<T>(T, SortedSet<T>)'`

* couple more fixes

* Update nuget.config to use dotnet9 sources instead of dotnet8

* Remove unnecessary package reference to Microsoft.DotNet.XunitAssert

* Address xUnit1030 warning.

`error xUnit1030: Test methods should not call ConfigureAwait(false), as it may bypass parallelization limits. Omit ConfigureAwait, or use ConfigureAwait(true) to avoid CA2007. (https://xunit.net/xunit.analyzers/rules/xUnit1030)`

* Ignore some lint warnings for eng/common/template-guidance.md from arcade

* cleanup

* Fix AzureFunctionsEndToEnd

* Track changes for Aspire.Hosting.Azure.Functions

* Fix CA2007: src\Aspire.Hosting\Health\ResourceHealthCheckScheduler.cs(38,45): error CA2007: Consider calling ConfigureAwait on the awaited task

* Add dependency to Microsoft.DotNet.XliffTasks from dotnet/arcade

* Add back skipping hosting.sdk, and projectTemplates packages

.. in workload testing as it is required for the internal build.

`Aspire.Hosting.Sdk.Msi.arm64.9.0.0-preview.4.24460.2.nupkg, Aspire.Hosting.Sdk.Msi.x64.9.0.0-preview.4.24460.2.nupkg, Aspire.Hosting.Sdk.Msi.x86.9.0.0-preview.4.24460.2.nupkg, Aspire.ProjectTemplates.Msi.arm64.9.0.0-preview.4.24460.2.nupkg, Aspire.ProjectTemplates.Msi.x64.9.0.0-preview.4.24460.2.nupkg, Aspire.ProjectTemplates.Msi.x86.9.0.0-preview.4.24460.2.nupkg`

* [tests] Increase the default timeout from 10mins to 15mins for basictests

.. like the various hosting integration tests. The run time can vary
especially if docker needs to fetch an image.