Fix xUnit2029 warning in tests
`test/Generators/Microsoft.Gen.Logging/Unit/EmitterTests.cs(56,9): error
xUnit2029: (NETCORE_ENGINEERING_TELEMETRY=Build) Do not use
Assert.Empty() to check if a value does not exist in a collection. Use
Assert.DoesNotContain() instead.
(https://xunit.net/xunit.analyzers/rules/xUnit2029)`