Update TFMs (#4394)
* Revise supported TFMs

* Drop support for .NET Core 3.1
* Add support for .NET 6.0
* Run tests for only supported TFMs - i.e., net462;net6.0;net8.0

* warning IDE0028: Collection initialization can be simplified (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0028)

* Suppress TBD warnings, see https://github.com/dotnet/extensions/issues/4395

* error CS0618: 'HttpRequestMessage.Properties' is obsolete: 'HttpRequestMessage.Properties has been deprecated. Use Options instead.'

* Fix tests

* warning NETSDK1212: IsTrimmable is not supported for the target framework